keys:
  - &iosmanthus age12409ktkdynl48p38wz45pu2s25kmffsw4p9d9vgt3xmmwl8f7q7sjlxyrs
  - &aws-lightsail-0 age1hzjj23k8ckesm7aqvelndn2hkywts84892tp0xhl0vj7kz7kugcsr9fepp
  - &gcp-instance-0 age1yryaysvqelzl2zuryss8ek7tcx6wjp4n5n79p6tyvjfrn4utg3uq9nvre6
  - &gcp-instance-1 age1rlp2q8vyyng2vkjdf80p6l0fhzkte8x7hns53dlan57ev7e2scqq4pg9qu
creation_rules:
  - key_groups:
      - age:
          - *iosmanthus
          - *aws-lightsail-0
          - *gcp-instance-0
          - *gcp-instance-1
