keys:
  - &iosmanthus age12409ktkdynl48p38wz45pu2s25kmffsw4p9d9vgt3xmmwl8f7q7sjlxyrs
  - &gcp-instance-0 age1xmtu762yzwj7498c3un3tx8ct9zcg2cz560vek43mqdnmtuul3ks0lyca4
creation_rules:
  - key_groups:
      - age:
          - *iosmanthus
          - *gcp-instance-0
