keys:
  - &iosmanthus age12409ktkdynl48p38wz45pu2s25kmffsw4p9d9vgt3xmmwl8f7q7sjlxyrs
  - &gcp-instance-0 age1yryaysvqelzl2zuryss8ek7tcx6wjp4n5n79p6tyvjfrn4utg3uq9nvre6
creation_rules:
  - key_groups:
      - age:
          - *iosmanthus
          - *gcp-instance-0
