keys:
  - &iosmanthus age12409ktkdynl48p38wz45pu2s25kmffsw4p9d9vgt3xmmwl8f7q7sjlxyrs
  - &gcp-instance-1 age1ehxtx7tkgtqwxdwty9as7yjpa08j9y2c2hhtww0hknteasehju3q2xh4fv
creation_rules:
  - key_groups:
      - age:
          - *iosmanthus
          - *gcp-instance-1
