keys:
  - &iosmanthus age12409ktkdynl48p38wz45pu2s25kmffsw4p9d9vgt3xmmwl8f7q7sjlxyrs
  - &gcp-instance-1 age1rlp2q8vyyng2vkjdf80p6l0fhzkte8x7hns53dlan57ev7e2scqq4pg9qu
creation_rules:
  - key_groups:
      - age:
          - *iosmanthus
          - *gcp-instance-1
