keys:
  - &iosmanthus age12409ktkdynl48p38wz45pu2s25kmffsw4p9d9vgt3xmmwl8f7q7sjlxyrs
  - &lego age1ad7q0mhaks0r3rd2cpxf35t9al8up2e3fqkl2pyuf49ekyqnv4ssc8j6ak
creation_rules:
  - key_groups:
      - age:
          - *iosmanthus
          - *lego
