keys:
  - &iosmanthus age12409ktkdynl48p38wz45pu2s25kmffsw4p9d9vgt3xmmwl8f7q7sjlxyrs
  - &aws-lightsail-0 age1hzjj23k8ckesm7aqvelndn2hkywts84892tp0xhl0vj7kz7kugcsr9fepp
  - &gcp-instance-0 age1ycgzpgz4vscwfknf2tyvr65c6t95xeffx3qp50r00u83xlpfmgpsx4gyr5
creation_rules:
  - key_groups:
      - age:
          - *iosmanthus
          - *aws-lightsail-0
          - *gcp-instance-0
