grafana:
    prometheus-basic-auth: ENC[AES256_GCM,data:ms0WgYv4LVGIYNCXOtnXj1Nje3sEw2Knj6F84ww2jZe0s+v7jyeH1A3Bj75TwRkNNfgOgsTOEbuKKyfBW8bHLWYkdYaLE5F6TOwWdBB4G0uuaR4pH4O1eTrHh6mOffDcefYTv8Lgf814N9ZhSQZHjFf1I3R0Xec9pKnuyrlo8nccCDqiOuTXNMjkZCg5uWzxou0e4gnqnbCLlKni6AdknUVMZQX6gu9YqdHVqUdmUbvnOAy9pRLrsth63gq7OcIbUtK0m/hNazoFOpZ/+LNYlH7Sb9Vjt1lMnc00Doa6BSu7bxVvkUsBwyhnIhg=,iv:TkfpMqxLH4uQ+QCPH8zxE4cnoRf/pKPKYDzojmcrur8=,tag:INOu+MgzV5+/whF/vKruFQ==,type:str]
    promtail-basic-auth: ENC[AES256_GCM,data:XEripshQRTprKkVBz7hdkWQGggEVpH08vtOJqwGMO/WfEUm9hgc49WIMoOBVhcNTC4TWJmlCtnaLeAh78efCHIIS4CLlXTKbYJw+SPUv43mQoL8aqNJQIQi+UtJJDxhDAqAKQXWm8Ae8BvxVc6McsJ0zOkfsrdwrG2oTeQPIrMBaCrT/Xp8lDxD3Onysf+fzt4t4zHPLJq2FzwzpRdOIkHZtLoeKjbDY1TWImy3cDN97ekDw/Lcsah3MSsvsThf9ludHB9MQfpVNwQo/ryOdFihNQDTVcs7hD8C2PxposSuFyHlOOv6Vfg4NuCw=,iv:+akd0tM5xZ2RcTVlHWx877eItBH/9lwumO6B3F6QGN8=,tag:hdJgwgBxukQa7CppTBgsfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12409ktkdynl48p38wz45pu2s25kmffsw4p9d9vgt3xmmwl8f7q7sjlxyrs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMWcvdU5XWDlxV0FaYWRX
            UTc2dDRpZCtNSTd3RmRqTTA3M2JRaHFicUhNCkg0L01VYWg4eFkzVEhEOXBsOWIy
            Sk9yWVRaK1FrYWhWeVEySklxNktxdkkKLS0tIGJmek4zdWlwNUw5ZE1CS2xyYlRx
            NVJXNXYvREdjOEdSQ0lWcE50SDJmemcKlAja2mYmGSD+rg+NtuQvlsK8le4/8qRG
            altwQV53J/B5Lbk1wGCji61hQVzgr64aBT0RwxJfenFh0mZPO7oCHA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hzjj23k8ckesm7aqvelndn2hkywts84892tp0xhl0vj7kz7kugcsr9fepp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNL1VXOCtuY2hvbE5ZaFA0
            RkU5VVhsVVZXbkZiTkE3Wm5Cem4zaUNyMlM0Clh6cFRFWVB2b0E1enpVM2VjYnZG
            eFEwejNraVVWY3dzVTVqb3QrY3JnL0UKLS0tIGc3RjU2SWNpKytVTkMraTloRWsr
            clRHU043OThjTkV4Uzh3Wk10dUFsNW8KR5NI6VG83yyXt+0doVjPc/rILRdEyHGR
            /T7mhceQm9gjNVTgi3L5kKsq6anWnjDBvFEsVEj9nL0rMuRLRxK4MQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ycgzpgz4vscwfknf2tyvr65c6t95xeffx3qp50r00u83xlpfmgpsx4gyr5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYUdvTXhsbk5XZGR1L1N4
            RE43NnJ5QmJ4a0IvZVEzcTRmd0c3Q21IeWlJClJEWTJINGd3VXphYWtGT2tBcEYw
            V3JKTmhpQU5NZ1NieTMxUWZSMEFsY3MKLS0tIFY3WDA3L2FqZUh2Vzl0YTRLUHA3
            YWRMYVZWZFBmK3FnbDU1ZHZNMGhiYXMK/Txgz3EHsRecvpp3zBpChWZGg2dxKGW8
            LYoRc1hNVrhK7xhVKKLzOxmj/NhcYoP9sIG284+qgBaVFdcq4NbNiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-27T04:15:03Z"
    mac: ENC[AES256_GCM,data:40ulBxJAAHSzThahMCwLCe0DRD9vXx+Q2HEj9aCWn1H99PJBa9j8hAdzCLtI370VleLaMJkFdsQchdspBriqn2br5gevMREmAYcn5FuQwoqOtOdIT+Agk9i5FLEFZnT7hkTEjVsxWR/+EBBf/mdM6D5sJ2Us36GYygKg9va/gZA=,iv:U2wQ8msRZK/6kZkH/uMuwIOPdwdlsO1/efDzsCfNY2o=,tag:+847v/JtizqBOXp4d6Ci3A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
