grafana:
    prometheus-basic-auth: ENC[AES256_GCM,data:bTmHJz22NWJbGat4Op2huMWF2IJRAjmDsyi+/W78y0QcfetYZ4wfM16JFw2dcXubi+ZugrP9lD1ipLo3PHS4eb4tmAQLwX8xS5m97RyqvratMtlgZC4qiIVwLoa73GBjMwaVliMvbPrefZZWKWLJVgvFMR5j6zKyV8mjhmdBK8FYzptLCOsHZTzal7UKQYykx5a5uL5OK6i+OxnI/jf8c8UWwoYtmVBHbNP60NEff5fyM1/4IgbduQmIwYUHC6UW2HwoI2LN4Jr7r7uGgY7qWrx4ev+ZCauD1/ZfDEsZH4myaqCf29mM/Sr91X4=,iv:YpblG9dJVQzdghrJ6p10ss71ii1JtWyBVutJRAIyLSU=,tag:uAXwKJDA7PQjU3m4Vbv0SQ==,type:str]
    promtail-basic-auth: ENC[AES256_GCM,data:1Bc+BZ+DgC4RZ9Cht0JkNhTxBcDzCsy07qY07TPcYi6I6jmkArfmwRW7AjBKvM++WFSdxB1MWHeQHP5gEp1L7GsfCK3YSG9+RxfC63KIELpgEdF89lIp6KffRe03LjrGG09VQAdnpXdvEcGMGy9ixfNgTC70EeMf+iYi6AMVezM3WIpPc54LU0j/OGt0WRQLAjRJkM375i2sIPOn/zkBRyPWnrXMJhMUmMoBH9UV9RkWkM94pa8XTfXkzfwM9oqRPP9s5joQgIZp2aaGOaO3jmDxHso/8FZKxKbY6ovl2kqMmzRYCz1QDflSXWA=,iv:+vXB0TevfqRJlIZ2IzJyzxHlcFwh7/Q51KP8GEi2A9A=,tag:5SGXMjpsN8Jqgo2XZA64Jg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12409ktkdynl48p38wz45pu2s25kmffsw4p9d9vgt3xmmwl8f7q7sjlxyrs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdXJqVnlhNzQrckxkRTNP
            RVUxZUlvc1FObXFzdnRSWmVvQ0VMUk41VFhJClFwbm5LcEticE1CTlFJT1U2cGE3
            dmFQdk10UWVtMTdXQ0dVZlU0c2hXOU0KLS0tIDBtN0d0OC9ZU2RJdHJXalRYU1B4
            TDNWUXJyME1qK1ZKVEt0ajFRN0xRUGMKbJmwE6xk3/iVD3wECDDC8btOhWo5+DMd
            kSPGE3u7WiAc0DI//VACNJcHhA+IapH/FwLAn6Vly77Px1VnNvV27g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hzjj23k8ckesm7aqvelndn2hkywts84892tp0xhl0vj7kz7kugcsr9fepp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OVJ1Y3RXTktUN24wOUdZ
            VXhyVk50aHhmRFc3SnVwWitvWHhsMFZUam1FCmM3L05QMnlPc1pYN0dVMXZ6YjZV
            bDVZSUtDZFNWNE0rYlprdTZDYTdaalUKLS0tIDRiMC84ei9IU1lNRkI5dWQ1eW53
            cFAwOGRyN0JRdjV0VHZ3UThZamNKRHcKY8npufWaX8Lpfw3As/BFQ95zfpw8KjDI
            zmPznDuQaVdI1guF/LIA2PHzToMO82IZ1ih0PZMeSIH2U9KJmH97Zw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ycgzpgz4vscwfknf2tyvr65c6t95xeffx3qp50r00u83xlpfmgpsx4gyr5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMHJ6YzNIckRxbEczd1VI
            bCtuTzBmaEVRUDdaWmRCUTZFOG9obXFCdlJrCkMvSlYyZDZBWisrZWdkcnVNcFE3
            cTV3MHZpSzgyUDhBTElOWS9sMUxySjAKLS0tIHIrQ3EwNTdEQmFJSUZoSkJHSHRR
            YVVhaytmREFjWXcvVkZ5eDRHNld2NEUK6dTqFeFwYffxvzAaWLbRhx9UNiHwmfbB
            yyqNK0WfWEzSJd0CQieTyn6enVZp1yvPJMpAfGaYzBpV26aLZOZeEA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12laakc7kq4pndwjs8syf87jtcjc95hshsyhm89pj78pc5t7agueql5juwk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweXFjU2w4MlNTWVNDR2dJ
            azVOR1drYmR0Y1pmeW5jMENnWlRwTC9BSjIwCmJzVnVkcGlHVFMxQVpUMUR3WGVl
            SmNjcFFrdC9NVHNRaHVKQVRJVmpndkUKLS0tIE56N3Q5c0JyZVR5LzVqYWlQclEz
            L2IzN05RSTFxUzFtem4zSDFVZlhGd1EKwlP3eMwVRw8UqzTUJJ4+kDdWNBaMfPjh
            0mVwBqubWHzyyi7tS1CU1nWRZSk6VpArGRDW0FMteWOOIaTKaock8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10zmaa6d5pwsqlxhc23e5ytz66k5nfxhry7fxvtayn0t5jfnl5yws4qe7pt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeThrNmRHNERwRTlkWExX
            Wk5rc0d6dlNrTVZuZnpEV3lFWmw5UFprdWswClNoN0RpWDZmY0N5TFVqMGNpVC9a
            dUJtOFlFUU0yRkJ4UUszMUxtaXo4SzgKLS0tIHlobnRxTWovSW4wbStJK0JPcStQ
            WUhsQ1BOeFZsU05nNXFBVDluQWE3MDAKawCWP7MzEFBJui06uaaTTCIJ8PiKL4hF
            nyq397s4juUXwB6OdxJ9LFpfPRPrVtqV2A47OxDTZ03cwgwEslc9kQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-10T04:18:27Z"
    mac: ENC[AES256_GCM,data:avqkza9BVG/BD8NoSzF1Ydh+kiyXFzQyx2dg7CaOASCgoG/d3aKNgtwqvcRUEhxifKlOOPAbnMY5F3UPjDeZwL6mhm4VZJ3DUhh0YJsxanBro90rjRm1qRA18rLOVrXOgtzNYgIxzaOlIrBlm13qc4odsxUZorkozkk9z9dtXi8=,iv:KJpqmG1zznZhwt4dDaRU5LhXOrDSvQSNK9eDnOKQ5G4=,tag:uKJK4ih/Bfd6KzYZKt9zjQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
