keys:
  - &iosmanthus age12409ktkdynl48p38wz45pu2s25kmffsw4p9d9vgt3xmmwl8f7q7sjlxyrs
  - &aws-lightsail-0 age1hzjj23k8ckesm7aqvelndn2hkywts84892tp0xhl0vj7kz7kugcsr9fepp
  - &gcp-instance-0 age12rc72jm8h7js6qkxucwg8z7k9gz0w5vyavj4tpeyqphrddvjvsns37tkzq
  - &gcp-instance-1 age1ehxtx7tkgtqwxdwty9as7yjpa08j9y2c2hhtww0hknteasehju3q2xh4fv
creation_rules:
  - key_groups:
      - age:
          - *iosmanthus
          - *aws-lightsail-0
          - *gcp-instance-0
          - *gcp-instance-1
