keys:
  - &iosmanthus age12409ktkdynl48p38wz45pu2s25kmffsw4p9d9vgt3xmmwl8f7q7sjlxyrs
  - &aws-lightsail-0 age1hzjj23k8ckesm7aqvelndn2hkywts84892tp0xhl0vj7kz7kugcsr9fepp
creation_rules:
  - key_groups:
      - age:
          - *iosmanthus
          - *aws-lightsail-0
