keys:
  - &iosmanthus age12409ktkdynl48p38wz45pu2s25kmffsw4p9d9vgt3xmmwl8f7q7sjlxyrs
  - &lego-router age1gt6fyh2fs87yyu2gnaqmzj3f0pdad9ecx29lhf83un0z94ng24hqn3pg4n
creation_rules:
  - path_regex: sing-box
    key_groups:
      - age:
          - *iosmanthus
          - *lego-router
  - key_groups:
      - age:
          - *iosmanthus
