keys:
  - &iosmanthus age12409ktkdynl48p38wz45pu2s25kmffsw4p9d9vgt3xmmwl8f7q7sjlxyrs
  - &gcp-instance-2 age10zmaa6d5pwsqlxhc23e5ytz66k5nfxhry7fxvtayn0t5jfnl5yws4qe7pt
creation_rules:
  - key_groups:
      - age:
          - *iosmanthus
          - *gcp-instance-2
