# Expression generated by update.sh; do not edit it by hand!
{ stdenv, callPackage, ... }@args:

let
  pname = "brave-nightly";
  version = "1.79.8";

  allArchives = {
    # https://github.com/brave/brave-browser/releases/download/v1.79.8/brave-browser-nightly-1.79.8-1.x86_64.rpm
    # https://github.com/brave/brave-browser/releases/download/v1.79.8/brave-browser-nightly_1.79.8_amd64.deb
    x86_64-linux = {
      url = "https://github.com/brave/brave-browser/releases/download/v${version}/brave-browser-nightly_${version}_amd64.deb";
      hash = "sha256-OGP1O52z+rhsmCGh+64gpNEjnf50cbu0o1u5KvfMJDY=";
    };
  };

  archive =
    if builtins.hasAttr stdenv.system allArchives then
      allArchives.${stdenv.system}
    else
      throw "Unsupported platform.";

in
callPackage ./make-brave.nix (removeAttrs args [ "callPackage" ]) (
  archive
  // {
    inherit pname version;
  }
)
